version: '3'

services:
  listings:
    build: ./
    depends_on:
      - 'listingdatabase'
    ports:
      - '3003:3003'

  listingdatabase:
    image: mongo:latest

  mongo-seed:
    build: ./
    depends_on:
      - 'picturedatabase'
    command: sh -c "npm run seed"