version: 2
jobs:
  build:
    branches:
      only:
        - create-server-index.js
    working_directory: ~/server
    docker:
      - image: circleci/node:8.15
    steps:
      - checkout
      - run: npm install
      # run tests!
      # - run: test

